/**
 * Mock data for development
 * To be replaced with real TMDB data in Phase 3
 */

export const mockMovies = [
  {
    id: 1,
    title: 'The Dark Knight',
    posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations.',
    releaseDate: '2008-07-18',
    voteAverage: 8.5,
    genres: ['Action', 'Crime', 'Drama'],
    runtime: 152,
  },
  {
    id: 2,
    title: 'Inception',
    posterPath: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life.',
    releaseDate: '2010-07-16',
    voteAverage: 8.4,
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    runtime: 148,
  },
  {
    id: 3,
    title: 'The Shawshank Redemption',
    posterPath: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    overview: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    releaseDate: '1994-09-23',
    voteAverage: 8.7,
    genres: ['Drama', 'Crime'],
    runtime: 142,
  },
  {
    id: 4,
    title: 'Interstellar',
    posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    releaseDate: '2014-11-07',
    voteAverage: 8.3,
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    runtime: 169,
  },
  {
    id: 5,
    title: 'The Matrix',
    posterPath: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/icmmSD4vTTDKOq2vvdulafOGw93.jpg',
    overview: 'A computer hacker learns about the true nature of his reality and his role in the war against its controllers.',
    releaseDate: '1999-03-31',
    voteAverage: 8.2,
    genres: ['Action', 'Sci-Fi'],
    runtime: 136,
  },
  {
    id: 6,
    title: 'Pulp Fiction',
    posterPath: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    releaseDate: '1994-10-14',
    voteAverage: 8.5,
    genres: ['Crime', 'Drama'],
    runtime: 154,
  },
  {
    id: 7,
    title: 'Forrest Gump',
    posterPath: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/7c9UVPPiTPltouxRVY6N3n8HbMx.jpg',
    overview: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man.',
    releaseDate: '1994-07-06',
    voteAverage: 8.5,
    genres: ['Drama', 'Romance'],
    runtime: 142,
  },
  {
    id: 8,
    title: 'Fight Club',
    posterPath: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    overview: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much more.',
    releaseDate: '1999-10-15',
    voteAverage: 8.4,
    genres: ['Drama', 'Thriller'],
    runtime: 139,
  },
];

export const mockTVShows = [
  {
    id: 101,
    name: 'Breaking Bad',
    posterPath: 'https://image.tmdb.org/t/p/w500/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    overview: 'A high school chemistry teacher turned methamphetamine producer partners with a former student to secure his family\'s future.',
    firstAirDate: '2008-01-20',
    voteAverage: 9.0,
    genres: ['Crime', 'Drama', 'Thriller'],
    numberOfSeasons: 5,
  },
  {
    id: 102,
    name: 'Stranger Things',
    posterPath: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    overview: 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces.',
    firstAirDate: '2016-07-15',
    voteAverage: 8.6,
    genres: ['Sci-Fi', 'Horror', 'Drama'],
    numberOfSeasons: 4,
  },
  {
    id: 103,
    name: 'Game of Thrones',
    posterPath: 'https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
    overview: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns.',
    firstAirDate: '2011-04-17',
    voteAverage: 8.3,
    genres: ['Drama', 'Fantasy', 'Adventure'],
    numberOfSeasons: 8,
  },
  {
    id: 104,
    name: 'The Crown',
    posterPath: 'https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/wHs0xWT4YdK7pBaNpRyfzSDLdkc.jpg',
    overview: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.',
    firstAirDate: '2016-11-04',
    voteAverage: 8.1,
    genres: ['Drama', 'History'],
    numberOfSeasons: 6,
  },
  {
    id: 105,
    name: 'The Witcher',
    posterPath: 'https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/1R016Fv2zXEw2X6xKzMdmLx4R.jpg',
    overview: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
    firstAirDate: '2019-12-20',
    voteAverage: 8.0,
    genres: ['Fantasy', 'Adventure', 'Action'],
    numberOfSeasons: 3,
  },
  {
    id: 106,
    name: 'The Mandalorian',
    posterPath: 'https://image.tmdb.org/t/p/w500/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/9ijMGlJKqcslswWUzTEwScm82Gs.jpg',
    overview: 'A lone bounty hunter makes his way through the outer reaches of the galaxy, far from the authority of the New Republic.',
    firstAirDate: '2019-11-12',
    voteAverage: 8.4,
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    numberOfSeasons: 3,
  },
];

export const mockHeroContent = {
  id: 1,
  title: 'The Dark Knight',
  type: 'movie' as const,
  overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  backdropPath: 'https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
  voteAverage: 8.5,
  releaseDate: '2008-07-18',
  genres: ['Action', 'Crime', 'Drama', 'Thriller'],
};

export const mockCast = [
  {
    id: 1,
    name: 'Christian Bale',
    character: 'Bruce Wayne / Batman',
    profilePath: 'https://image.tmdb.org/t/p/w185/3qx2QFUbG6t6IlzR0F9k3Z6Yhf7.jpg',
  },
  {
    id: 2,
    name: 'Heath Ledger',
    character: 'Joker',
    profilePath: 'https://image.tmdb.org/t/p/w185/5Y9HnYYa9jF4NunY9lSgJGjSe8E.jpg',
  },
  {
    id: 3,
    name: 'Aaron Eckhart',
    character: 'Harvey Dent / Two-Face',
    profilePath: 'https://image.tmdb.org/t/p/w185/dREOZKnT5qroLwkcfR8Hrf6bTFQ.jpg',
  },
  {
    id: 4,
    name: 'Michael Caine',
    character: 'Alfred Pennyworth',
    profilePath: 'https://image.tmdb.org/t/p/w185/bVZRMlpjTAO2pJK6v90buFgVbSW.jpg',
  },
  {
    id: 5,
    name: 'Maggie Gyllenhaal',
    character: 'Rachel Dawes',
    profilePath: 'https://image.tmdb.org/t/p/w185/ljw99CRCDGq8LLQn1V6Gr7GymTJ.jpg',
  },
  {
    id: 6,
    name: 'Gary Oldman',
    character: 'James Gordon',
    profilePath: 'https://image.tmdb.org/t/p/w185/2v9FVVBUrrkW2m3QOcYkuhq9A6o.jpg',
  },
];

// Content rows for homepage
export const mockContentRows = [
  {
    id: 'trending',
    title: 'Trending Now',
    items: mockMovies.slice(0, 6),
  },
  {
    id: 'popular',
    title: 'Popular on MyStream',
    items: [...mockMovies.slice(3, 8), ...mockTVShows.slice(0, 1)],
  },
  {
    id: 'top-rated',
    title: 'Top Rated',
    items: mockMovies.slice(1, 7),
  },
  {
    id: 'tv-shows',
    title: 'Popular TV Shows',
    items: mockTVShows,
  },
  {
    id: 'action',
    title: 'Action & Adventure',
    items: mockMovies.filter((m) => m.genres.includes('Action')),
  },
  {
    id: 'drama',
    title: 'Drama',
    items: [...mockMovies.filter((m) => m.genres.includes('Drama')).slice(0, 4)],
  },
];
